### ISSUE TITLE
Board Detail API 구현

### ISSUE THREAD

**Issue by raxkson** [fancuk/fan.catholic.ac.kr-backend#79]
Board Detail API 구현

- GET
- api/board/

보통 게시글 번호로 호출을 하는데 
우리가 게시글 번호를 지정하지 않아서 GET 파라미터가 길어질 우려가 있음 
그리고 제목이 같다고 중복 처리 하기가 어려움
GET이 길어지면 보기좋지 않은데 의견좀..

**Comment by raxkson** [comment]
GET Parameter에 모든 값 넣어서 확인 하도록 함

**Comment by O-Seonsik** [comment]
모든 값이라고 하기는 조금 무리가 따릅니다. 아까 제가 설명을 조금 잘못했을 수 도 있는데 writer, title, date 세가지 정보만 어떤 게시물을 특정하기 위한 파라미터로 이용하면 될 것 같습니다! 혹시 문제있거나 이상하다고 느껴지면 Slack 부탁드려염 @raxkson
